<?=$this->view->getVar('breadcrumbs')->render()?>

<h1 class="page-header">Email verification</h1>
<?if ($this->view->getVar('user')) {?>
<p>Thank you <?=$this->view->getVar('escaper')->escapeHtml($this->view->getVar('user')->name)?></p>
<p>You've successfully confirm your email and you could proceed to <a href="/login/index">login page</a> and start using our system.</p>
<p>Have fun!</p>
<?} else {?>
<p>Oops! Something goes wrong!</p>
<p>The email you've provided was not verified successfully. Please, go to the <a href="/confirmemail/initverify">verification page</a> and try one more time.</p>
<p>Sorry for inconvenience.</p>
<?}?>
