<html>
<head>
</head>
<body>
<?if ($this->view->getVar('user')) {?>
	Thank you <?=$this->view->getVar('user')->name?>!<br /><br />
	
	You've successfully confirm your email and you could proceed to <a href="/user/signin">login page</a> and start using our system.<br /><br />
	
	Have fun!
<?} else {?>
	Oops!<br /><br />
	
	Something goes wrong!
	The email you've provided was not verified successfully. Please, go to the <a href="/confirmemail/initverify">verification page</a> and try one more time.<br /><br />
	
	Sorry for inconvenience.
<?}?>
</body>
</html>
