<html>
<head>
<?php echo \Phalcon\Tag::javascriptInclude("js/config.js"); ?>
</head>
<body>
<?php use Phalcon\Tag as Tag; ?>
<?=Tag::form(array($this->view->form->getAction())) ?>

	<p>
		<label for="email">Email<?php if ($form->hasMessagesFor('email')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('email')[0]?></strong>)<?php } ?><?php if ($this->view->getVar('emailRegistered')) { ?> (<strong style="color:red;">This email already registered</strong>)<?php } ?>:</label>
		<?php echo $form->render('email') ?>
	</p>

	<p><?php if ($this->view->captcha->getError()) ?><span style="color:red; font-weight:bold"><?php echo $this->view->captcha->getError() ?></span>
		<?php echo $this->view->captcha->getHtml()?>
	</p>

	<p>
		<?=$this->view->form->render('submit')?>
	</p>

<?=Tag::endForm ()?>
</body>
</html>
