<?php use Phalcon\Tag as Tag; ?>

<h1 class="page-header">Reset password</h1>

<?=Tag::form(array($this->view->form->getAction())) ?>

	<div class="form-group">
		<label for="<?=$this->view->form->get('email')->getName()?>"><?=$this->view->form->get('email')->getLabel()?></label>
<?=$form->render('email') ?>
		<span style="font-size:small; color:grey;display:block;">* Please, use only primary email for your account to login.</span>
		<span class="help-block">
<?php
// TODO: add check if email exist
if ($form->hasMessagesFor($form->get('email')->getName())) {
	echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('email')->getName())->offsetGet(0)->getMessage());
}
?>
		</span>
	</div>

	<div class="form-group">
<?=$this->view->captcha->getHtml()?>
		<span class="help-block">
<?if ($this->view->captcha->getError()) echo $this->view->captcha->getError();?>
		</span>
	</div>

	<div class="form-group">
<?=$form->render('submit') ?>
	</div>

<?=Tag::endForm ()?>
