<html>
<body>
Доброго дня!<br /><br />

Ваш email було використано для відновлення пароля на ресурсі <?=$server?>.<br />
Для підтвердження будь ласка перейдіть <a href="<?=$server?>/confirmemail/resetpassword?id=<?=urlencode($primaryEmail->user_id)?>&code=<?=urlencode($primaryEmail->createVerificationCode(UserVerificationCodes::REASON_RESET_PASSWORD)->getVerificationCode())?>">сюди</a> або відкрийте наступне посилання в бровзері:<br /><br />

<?=$server?>/confirmemail/resetpassword?id=<?=urlencode($primaryEmail->user_id)?>&code=<?=urlencode($primaryEmail->getVerificationCode(UserVerificationCodes::REASON_RESET_PASSWORD)->getVerificationCode())?><br /><br />

Наведений лінк діє 5 годин.<br /><br />

Якщо Ви не намагались відновити Ваш пароль проігноруйте цей лист.<br /><br />

Дякую,<br />
Адміністрація
</body>
</html>
