<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">G44</a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active"><a href="/home">Home</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
<? if ($this->session->get('auth')->isAuthenticated()) {?>
				<li><a href="/profile/index/<?=$this->session->get('auth')->getUserId()?>">Profile</a></li>
				<li><a href="/signout/index">Sign Out</a></li>
<? } else { ?>
				<li><a href="/register/index">Sign Up</a></li>
				<li><a href="/login/index">Sign In</a></li>
<? } ?>
			</ul>

		</div><!--/.nav-collapse -->
	</div>
</div>
