<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">G44</a>
		</div>
		<div class="collapse navbar-collapse">
<?
if ($this->session->get('auth')->isAuthenticated() 
	&& $this->session->get('auth')->getUserRole() != UsersRoles::ROLE_GUEST) {
?>
			<ul class="nav navbar-nav">
<?
if ($this->session->get('auth')->getUserRole() == UsersRoles::ROLE_ADMINISTRATOR) {
?>
				<li><a href="/useradmin">Users</a></li>
<? } ?>
			</ul>
<? } ?>
			<ul class="nav navbar-nav navbar-right">
<?
if ($this->session->get('auth')->isAuthenticated()) {
if ($this->session->get('auth')->getUserRole() != UsersRoles::ROLE_GUEST) {
?>
				<li><a href="/profile">Profile</a></li>
<? } ?>
				<li><a href="/signout/index">Sign Out</a></li>

<? } else { ?>
				<li><a href="/register/index">Sign Up</a></li>
				<li><a href="/login/index">Sign In</a></li>
<? } ?>
			</ul>

		</div><!--/.nav-collapse -->
	</div>
</div>
