<div class="page-header">
	<h1>This is dummy text</h1>
	<p class="lead">
		Bootstrap starter template. Use this document as a way to quickly start 
		any new project. All you get is this text and a mostly barebones HTML document.
	</p>
</div>
<p>
	Bootstrap starter template. Use this document as a way to quickly start 
	any new project. All you get is this text and a mostly barebones HTML document.
</p>
