<? use Phalcon\Tag as Tag; ?>

<?=$this->view->getVar('breadcrumbs')->render()?>

<h1 class="page-header">Change password</h1>
<?=$this->partial('partials/messages')?>
<?=Tag::form(array($this->view->form->getAction())) ?>

	<div class="form-group">
		<label for="<?=$form->get('new_password')->getName()?>"><?=$form->get('new_password')->getLabel()?>:</label>
<?=$form->render('new_password') ?>
		<span class="help-block">
<?
	if ($form->hasMessagesFor($form->get('new_password')->getName())) {
		echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('new_password')->getName())->offsetGet(0)->getMessage());
	}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('confirmPassword')->getName()?>"><?=$form->get('confirmPassword')->getLabel()?>:</label>
<?=$form->render('confirmPassword') ?>
		<span class="help-block">
<?
	if ($form->hasMessagesFor($form->get('confirmPassword')->getName())) {
		echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('confirmPassword')->getName())->offsetGet(0)->getMessage());
	}
?>
		</span>
	</div>

	<div class="form-group">
<?=$form->render('submit') ?>
	</div>

<?=Tag::endForm ()?>
