<h1 class="page-header">Forgot Password</h1>
<?=\Phalcon\Tag::form(array($this->view->form->getAction())) ?>

	<div class="form-group">
		<label for="<?=$form->get('email')->getName()?>"><?=$form->get('email')->getLabel()?>:</label>
		<?php echo $form->render('email') ?>
		<span style="font-size:small; color:grey;display:block;">* Please, use only primary email for your account to login.</span>
		<span class="help-block">
<?php
	if (isset($this->view->getVar('errors')[$form->get('email')->getName()])) {
		echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('email')->getName()]);
	}
?>
		</span>
	</div>

	<div class="form-group">
		<?php if ($this->view->captcha->getError()) ?><span style="color:red; font-weight:bold"><?php echo $this->view->captcha->getError() ?></span>
		<?php echo $this->view->captcha->getHtml()?>
	</div>

	<div class="form-group">
		<?php echo $form->render('submit') ?>
	</div>

<?=\Phalcon\Tag::endForm ()?>
