<? use Phalcon\Tag as Tag; ?>

<h1 class="page-header">Reset password</h1>

<?=Tag::form(array($this->view->form->getAction())) ?>

	<div class="form-group">
		<label for="<?=$form->get('password')->getName()?>"><?=$form->get('password')->getLabel()?>:</label>
<?=$form->render('password') ?>
		<span class="help-block">
<?
if ($form->hasMessagesFor($form->get('password')->getName())) {
	echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('password')->getName())->offsetGet(0)->getMessage());
}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('confirmPassword')->getName()?>"><?=$form->get('confirmPassword')->getLabel()?>:</label>
<?=$form->render('confirmPassword') ?>
		<span class="help-block">
<?
if ($form->hasMessagesFor($form->get('confirmPassword')->getName())) {
	echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('confirmPassword')->getName())->offsetGet(0)->getMessage());
}
?>
		</span>
	</div>

	<div class="form-group">
<?=$this->view->captcha->getHtml()?>
		<span class="help-block">
<?if ($this->view->captcha->getError()) echo $this->view->captcha->getError();?>
		</span>
	</div>

	<div class="form-group">
<?=$form->render('submit') ?>
	</div>

<?=Tag::endForm ()?>
