<h1 class="page-header">Reset Password</h1>
<?php $form = $this->view->form; echo $this->tag->form($form->getAction()) ?>

	<div class="form-group">
		<label for="<?=$form->get('password')->getName()?>"><?=$form->get('password')->getLabel()?>:</label>
		<?php echo $form->render('password') ?>
	</div></p>

	<div class="form-group">
		<label for="<?=$form->get('confirmPassword')->getName()?>"><?=$form->get('confirmPassword')->getLabel()?>:</label>
		<?php echo $form->render('confirmPassword') ?>
	</div>

	<div class="form-group">
		<?php if ($this->view->captcha->getError()) ?><span style="color:red; font-weight:bold"><?php echo $this->view->captcha->getError() ?></span>
		<?php echo $this->view->captcha->getHtml()?>
	</div>

	<div class="form-group">
		<?php echo $form->render('submit') ?>
	</div>

</form>
</body>
</html>
