<html>
<head>
<?php echo \Phalcon\Tag::javascriptInclude("js/config.js"); ?>
</head>
<body>
<?php $form = $this->view->form; echo $this->tag->form($form->getAction()) ?>

	<p>
		<label for="name">Username<?php if ($form->hasMessagesFor('name')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('name')[0]?></strong>)<?php } ?>:</label>
		<?php echo $form->render('name') ?>
	</p>

	<p>
		<label for="email">Email<?php if ($form->hasMessagesFor('email')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('email')[0]?></strong>)<?php } ?><?php if ($this->view->getVar('emailRegistered')) { ?> (<strong style="color:red;">This email already registered</strong>)<?php } ?>:</label>
		<?php echo $form->render('email') ?>
	</p>

	<p>
		<label for="password">Password<?php if ($form->hasMessagesFor('password')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('password')[0]?></strong>)<?php } ?>:</label>
		<?php echo $form->render('password') ?>
	</p>

	<p>
		<label for="repeatPassword">Repeat password<?php if ($form->hasMessagesFor('repeatPassword')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('repeatPassword')[0]?></strong>)<?php } ?>:</label>
		<?php echo $form->render('confirmPassword') ?>
	</p>

	<p><?php if ($this->view->captcha->getError()) ?><span style="color:red; font-weight:bold"><?php echo $this->view->captcha->getError() ?></span>
		<?php echo $this->view->captcha->getHtml()?>
	</p>

	<p>
		<?php echo $form->render('submit') ?>
	</p>

</form>
</body>
</html>
