<html>
<head>
<?=\Phalcon\Tag::javascriptInclude("js/config.js"); ?>
</head>
<body>
	<h1 class="page-header">Sign In</h1>

<? $form = $this->view->form; echo $this->tag->form($form->getAction()) ?>

<? if ($this->view->getVar('error')) {?>
	<p style="padding-left:0.5em; color:red; font-weight: bold; font-size:small;">
		* Login or password is wrong. Please try again.
	</p>
<? } ?>

	<div class="form-group">
		<label for="email">Email address<font style="color:red;">*</font></label>
<?=$form->render('email') ?>
		<p class="help-block">
			* Please, use only primary email for your account to login.
		</p>
		<p class="help-block">
<? if ($form->hasMessagesFor('email')) { ?> <strong style="color:red;"><?php echo $form->getMessagesFor('email')[0]?></strong><?php } ?><?php if ($this->view->getVar('emailRegistered')) { ?> <strong style="color:red;">This email already registered</strong><?php } ?>
		</p>
	</div>

	<div class="form-group">
		<label for="password">Password<font style="color:red;">*</font></label>
<?=$form->render('password') ?>
		<p class="help-block">
<? if ($form->hasMessagesFor('password')) { ?> <strong style="color:red;"><?php echo $form->getMessagesFor('password')[0]?></strong><?php } ?>
		</p>
	</div>

	<div class="form-group">
<? if ($this->view->getVar('captcha')) { ?>
		<label for="captcha">Captcha</label>
		<p>
<?=$this->view->captcha->getHtml()?>
<? if ($this->view->captcha->getError()) ?><span style="color:red; font-weight:bold"><?php echo $this->view->captcha->getError() ?></span>
		</p>
<? } ?>
	</div>

	<div class="form-group">
		<label for="remember_me">Remember me</label>
<?=$form->render('remember_me') ?>
	</div>

	<div class="form-group">
		<a href="/user/forgotpassword">Forgot password</a>?
	</div>
<?=$form->render('submit') ?>

</form>

</body>
</html>
