<html>
<head>
<?php echo \Phalcon\Tag::javascriptInclude("js/config.js"); ?>
</head>
<body>

	<h1 class="page-header">Sign Up</h1>

<?if ($this->view->getVar('sign_up_enable')) {?>

<?php $form = $this->view->form; echo $this->tag->form($form->getAction()) ?>

	<div class="form-group">
		<label for="name">Username</label>
		<?php echo $form->render('name') ?>
		<p class="help-block">
<?php if ($form->hasMessagesFor('name')) { ?> <strong style="color:red;"><?php echo $form->getMessagesFor('name')[0]?></strong><?php } ?>
		</p>
	</div>

	<div class="form-group">
		<label for="email">Email</label>
		<?php echo $form->render('email') ?>
		<p class="help-block">
<?php if ($form->hasMessagesFor('email')) { ?> <strong style="color:red;"><?php echo $form->getMessagesFor('email')[0]?></strong><?php } ?><?php if ($this->view->getVar('emailRegistered')) { ?> <strong style="color:red;">This email already registered</strong><?php } ?>
		</p>
	</div>

	<div class="form-group">
		<label for="password">Password</label>
		<?php echo $form->render('password') ?>
		<p class="help-block">
<?php if ($form->hasMessagesFor('password')) { ?> <strong style="color:red;"><?php echo $form->getMessagesFor('password')[0]?></strong><?php } ?>
		</p>
	</div>

	<div class="form-group">
		<label for="repeatPassword">Repeat password</label>
		<?php echo $form->render('confirmPassword') ?>
		<p class="help-block">
<?php if ($form->hasMessagesFor('repeatPassword')) { ?> <strong style="color:red;"><?php echo $form->getMessagesFor('repeatPassword')[0]?></strong><?php } ?>
		</p>
	</div>

	<div class="form-group">
		<label for="captcha">Captcha</label>
<? echo $this->view->captcha->getHtml()?>
<? if ($this->view->captcha->getError()) ?><span style="color:red; font-weight:bold"><?php echo $this->view->captcha->getError() ?></span>
	</div>

<?=$form->render('submit') ?>

</form>

<? } else { ?>

<p>Sorry but at current time registration was closed. Please try to sign up later.</p>
<p>Thanks!</p>

<? } ?>

</body>
</html>
