<? use Phalcon\Tag as Tag; ?>

<?=$this->view->getVar('breadcrumbs')->render()?>

<h1 class="page-header">Sign Up</h1>

<?if ($this->view->getVar('sign_up_enable')) {?>
<?=$this->partial('partials/messages')?>
<?=Tag::form(array($this->view->form->getAction())) ?>

	<div class="form-group">
		<label for="<?=$form->get('name')->getName()?>"><?=$form->get('name')->getLabel()?></label>
<?=$form->render('name') ?>
		<span class="help-block">
<?
if ($form->hasMessagesFor($form->get('name')->getName())) {
	echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('name')->getName())->offsetGet(0)->getMessage());
}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('email')->getName()?>"><?=$form->get('email')->getLabel()?></label>
<?=$form->render('email') ?>
		<span class="help-block">
<?
// collect input validation messages from form
if ($form->hasMessagesFor($form->get('email')->getName())) {
	echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('email')->getName())->offsetGet(0)->getMessage());
}

// notify user whether email is already registered
if ($this->view->getVar('emailRegistered')) { 
?>
			<span>This email is already used</span>
<? } ?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('password')->getName()?>"><?=$form->get('password')->getLabel()?></label>
<?=$form->render('password') ?>
		<span class="help-block">
<?
if ($form->hasMessagesFor($form->get('password')->getName())) {
	echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('password')->getName())->offsetGet(0)->getMessage());
}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('confirmPassword')->getName()?>"><?=$form->get('confirmPassword')->getLabel()?></label>
<?=$form->render('confirmPassword') ?>
		<span class="help-block">
<?php
if ($form->hasMessagesFor($form->get('confirmPassword')->getName())) {
	echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('confirmPassword')->getName())->offsetGet(0)->getMessage());
}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="captcha">Captcha</label>
<?=$this->view->captcha->getHtml()?>
<?if ($this->view->captcha->getError()) {?>
		<span class="help-block">
<?=$this->view->captcha->getError()?>
		</span>
<? } ?>
	</div>

<?=$form->render('submit') ?>

<?=Tag::endForm ()?>

<? } else { ?>

<p>Sorry but at current time registration was closed. Please try to sign up later.</p>
<p>Thanks!</p>

<? } ?>
