<?php use Phalcon\Tag as Tag; ?>
<h1 class="page-header">Profile::Add new email</h1>
<?=$this->partial('partials/messages')?>
<?=Tag::form(array($this->view->form->getAction())) ?>

	<div class="form-group">
		<label for="<?=$form->get('email')->getName()?>"><?=$form->get('email')->getLabel()?>:</label>
		<?php echo $form->render('email') ?>
		<span class="help-block">
<?php
	if ($form->hasMessagesFor($form->get('email')->getName())) {
		echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('email')->getName())->offsetGet(0)->getMessage());
	}
?>
		</span>
	</div>

	<div class="form-group">
		<?php echo $form->render('submit') ?>
	</div>

<?=Tag::endForm ()?>
