<?php use Phalcon\Tag as Tag; ?>
<?=Tag::form(array($this->view->form->getAction())) ?>

	<p>
		<label for="email">New Email<?php if ($form->hasMessagesFor('email')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('email')[0]?></strong>)<?php } ?>:</label><br />
		<?php echo $form->render('email') ?>
	</p>

	<p>
		<?php echo $form->render('submit') ?>
	</p>

<?=Tag::endForm ()?>

<br /><br />
<a href='/profile'>Back to Profile</a>
<br />
<a href='/home/index'>Back to Home</a>
