<h1 class="page-header">Profile</h1>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading"><strong>Name</strong></div>
	<!-- List group -->
	<ul class="list-group">
		<li class="list-group-item"><?=$this->view->getVar('escaper')->escapeHtml($this->view->getVar('user')->name)?>&nbsp;<a href='/profile/username'>Edit</a></li>
	</ul>
</div>

<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading"><strong>Password</strong></div>
	<!-- List group -->
	<ul class="list-group">
		<li class="list-group-item"><a href='/profile/password'>Edit</a></li>
	</ul>
</div>

<div class="panel panel-default">
	<div class="panel-heading"><strong>Emails</strong></div>

<?=$this->partial('partials/messages')?>

	<ul class="list-group">
<?
foreach ($this->view->getVar('user')->getEmails() as $email) {
?>
		<li class="list-group-item">
			<!-- Email to display -->
<?=$this->view->getVar('escaper')->escapeHtml($email->email)?>
			<!-- Bagdes -->
<?=$email->is_primary ? '&nbsp;<span class="label alert-success">Primary</span>' : ''?>
<?=$email->verified ? '' : '&nbsp;<span class="label alert-danger">Not Verified</span>'?>
			<!-- Control buttons -->
			<div class="pull-right">
				<!-- Set Primary button -->
<?=$email->verified && !$email->is_primary ? '<a href=/profile/setprimaryemail/?id='.$this->view->getVar('escaper')->escapeHtml($email->id).' type="button" class="btn btn-default btn-xs">Set Primary</a>' : ''?>
				<!-- Delete button -->
<?=$email->is_primary ? '' : '<a href=/profile/deleteemail/?id='.$this->view->getVar('escaper')->escapeHtml($email->id).' type="button" class="btn btn-danger btn-xs">Delete</a>';?>
			</div>
		</li>
<? } // end foreach ?>
		<li class="list-group-item">
			<a href='/profile/email'>Add new email</a>
		</li>
	</ul>
</div>
