<?php use Phalcon\Tag as Tag; ?>
<?=Tag::form(array($this->view->form->getAction())) ?>

	<p>
		<label for="old_password">Old password<?php if ($form->hasMessagesFor('old_password')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('old_password')[0]?></strong>)<?php } ?>:</label><br />
		<?php echo $form->render('old_password') ?>
	</p>

	<p>
		<label for="new_password">New password<?php if ($form->hasMessagesFor('new_password')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('new_password')[0]?></strong>)<?php } ?>:</label><br />
		<?php echo $form->render('new_password') ?>
	</p>

	<p>
		<label for="confirmPassword">Repeat new password<?php if ($form->hasMessagesFor('confirmPassword')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('confirmPassword')[0]?></strong>)<?php } ?>:</label><br />
		<?php echo $form->render('confirmPassword') ?>
	</p>

	<p>
		<?php echo $form->render('submit') ?>
	</p>

<?=Tag::endForm ()?>

<br /><br />
<a href='/profile'>Back to Profile</a>
<br />
<a href='/home/index'>Back to Home</a>