<?php use Phalcon\Tag as Tag; ?>
<h1 class="page-header">Profile::Change password</h1>
<?=Tag::form(array($this->view->form->getAction())) ?>

	<div class="form-group">
		<label for="<?=$form->get('old_password')->getName()?>"><?=$form->get('old_password')->getLabel()?>:</label>
		<?php echo $form->render('old_password') ?>
		<span class="help-block">
<?php
	if (isset($this->view->getVar('errors')[$form->get('old_password')->getName()])) {
		echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('old_password')->getName()]);
	}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('new_password')->getName()?>"><?=$form->get('new_password')->getLabel()?>:</label>
		<?php echo $form->render('new_password') ?>
		<span class="help-block">
<?php
	if (isset($this->view->getVar('errors')[$form->get('new_password')->getName()])) {
		echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('new_password')->getName()]);
	}
?>
		</span>
	</div>

	<div class="form-group">
		<label for="<?=$form->get('confirmPassword')->getName()?>"><?=$form->get('confirmPassword')->getLabel()?>:</label>
		<?php echo $form->render('confirmPassword') ?>
		<span class="help-block">
<?php
	if (isset($this->view->getVar('errors')[$form->get('confirmPassword')->getName()])) {
		echo $this->view->getVar('escaper')->escapeHtml($this->view->getVar('errors')[$form->get('confirmPassword')->getName()]);
	}
?>
		</span>
	</div>

	<div class="form-group">
		<?php echo $form->render('submit') ?>
	</div>

<?=Tag::endForm ()?>
