<?php use Phalcon\Tag as Tag; ?>
<h1 class="page-header">Profile::Change username</h1>
<?=$this->partial('partials/messages')?>
<?=Tag::form(array($this->view->form->getAction())) ?>

	<div class="form-group">
		<label for="<?=$form->get('name')->getName()?>"><?=$form->get('name')->getLabel()?>:</label>
		<?php echo $form->render('name') ?>
		<span class="help-block">
<?php
	if ($form->hasMessagesFor($form->get('name')->getName())) {
		echo $this->view->getVar('escaper')->escapeHtml($form->getMessagesFor($form->get('name')->getName())->offsetGet(0)->getMessage());
	}
?>
		</span>
	</div>

	<div class="form-group">
		<?php echo $form->render('submit') ?>
	</div>

<?=Tag::endForm ()?>
