<?php use Phalcon\Tag as Tag; ?>
<h1 class="page-header">Profile::Change username</h1>
<?=Tag::form(array($this->view->form->getAction())) ?>

	<p>
		<label for="name">New Username<?php if ($form->hasMessagesFor('name')) { ?> (<strong style="color:red;"><?php echo $form->getMessagesFor('name')[0]?></strong>)<?php } ?>:</label><br />
		<?php echo $form->render('name') ?>
	</p>

	<p>
		<?php echo $form->render('submit') ?>
	</p>

<?=Tag::endForm ()?>
