<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Blog's title</title>
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<?
echo \Phalcon\Tag::javascriptInclude("js/config.js");
if($this->view->getVar('bootstrap_enable')) {
//Bootstrap
echo Phalcon\Tag::stylesheetLink('//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css', false);
echo Phalcon\Tag::stylesheetLink('//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css', false);
echo Phalcon\Tag::stylesheetLink('css/theme.css');
}
?>
		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
<?=$this->partial('partials/navbar')?>
		<div class="container">
<?=$this->getContent() ?>
		</div>

		<div id="footer">
<?=$this->partial('partials/footer');?>
		</div>
<?
if($this->view->getVar('bootstrap_enable')) {
// Jquery
echo Phalcon\Tag::javascriptInclude('https://code.jquery.com/jquery.js', false);
//Bootstrap
echo Phalcon\Tag::javascriptInclude('//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js', false);
}
?>
	</body>
</html>
